/**
 * Background Process API client.
 *
 * Covers the six routes exposed by the platform ``background_process``
 * module (`interfaces/http/routes/background_process.py`):
 *
 *   GET    /api/background_process                            → list[Info]
 *   GET    /api/background_process/{id}                       → Info | 404
 *   GET    /api/background_process/{id}/logs                  → Logs | 404
 *   POST   /api/background_process/{id}/stop                  → Info | 404
 *   POST   /api/background_process/{id}/restart               → Info | 404
 *   POST   /api/background_process/session/{session}/stop     → {ok:true}
 *
 * The "start" verb is deliberately NOT exposed on plain HTTP (spawning a
 * background process must go through the LLM tool layer so it honours the
 * permission-ask + audit pipeline — see the route module docstring).
 *
 * Wire shapes are dataclass-as-dict serialisations of
 * ``qai.platform.background_process.ports.Info`` / ``Logs``.
 *
 * Used by the in-conversation ``BackgroundProcessCard`` to fetch authoritative
 * process state on mount and after user clicks (Stop / Restart / Logs).
 * Live updates flow through the global ``/api/events`` SSE stream
 * (``background_process.updated`` envelope; see `globalEvents.ts`).
 *
 * All functions return ``null`` on 404 so the card can render a "process
 * already retired" hint instead of throwing — long-running processes get
 * garbage-collected by the manager on session shutdown / TTL, and the card
 * may outlive its process.
 */

import { apiJson, type ApiRequestOptions } from "./http";
import { ApiError } from "./errors";

/** Lifecycle status reported by the manager. Mirrors
 *  ``qai.platform.background_process.ports.Status`` (a `Literal[...]`). */
export type BgpStatus =
  | "starting"
  | "running"
  | "ready"
  | "exited"
  | "failed"
  | "stopping"
  | "stopped";

/** Lifetime hint — v1 always emits ``"session"`` (process is bound to the
 *  spawning chat session and gets reaped on session end). */
export type BgpLifetime = "session";

/** Three timestamps the manager tracks for one process (ms epoch UTC). */
export interface BgpTime {
  readonly started: number;
  readonly updated: number;
  readonly ended: number | null;
}

/** Wire shape of one tracked background process — serialised
 *  ``Info`` dataclass (`dataclasses.asdict`). */
export interface BgpInfo {
  readonly id: string;
  readonly session_id: string;
  readonly pid: number | null;
  readonly command: string;
  readonly cwd: string;
  readonly description: string | null;
  readonly ports: ReadonlyArray<number>;
  readonly status: BgpStatus;
  readonly lifetime: BgpLifetime;
  readonly ready: boolean;
  readonly exit_code: number | null;
  readonly signal: string | null;
  /** Tail-bounded captured output (≤200 KiB, per platform contract). */
  readonly output: string;
  readonly time: BgpTime;
}

/** Wire shape of ``GET /{id}/logs`` — the full output tail + ids. */
export interface BgpLogs {
  readonly id: string;
  readonly session_id: string;
  readonly output: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Encode an id into a URL path segment. Background-process ids are
 *  generated by the manager (``bgp_<ulid>``) and contain only ASCII safe
 *  chars, but defensive encoding keeps the URL well-formed if the manager
 *  ever changes its id shape. */
function encodeId(id: string): string {
  return encodeURIComponent(id);
}

/** Run an ``apiJson`` call that may legitimately 404 (process already
 *  retired) and translate the 404 into ``null`` instead of throwing.
 *  Every other error propagates verbatim. */
async function tolerate404<T>(promise: Promise<T>): Promise<T | null> {
  try {
    return await promise;
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) {
      return null;
    }
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** ``GET /api/background_process`` — snapshot of every tracked process
 *  (no session filter; matches the route — sidebar consumer wants the
 *  global list). */
export async function fetchBgpList(
  opts?: ApiRequestOptions,
): Promise<ReadonlyArray<BgpInfo>> {
  return apiJson<ReadonlyArray<BgpInfo>>(
    "GET",
    "/api/background_process",
    undefined,
    opts,
  );
}

/** ``GET /api/background_process/{id}`` — one process or ``null`` (404). */
export async function fetchBgpInfo(
  id: string,
  opts?: ApiRequestOptions,
): Promise<BgpInfo | null> {
  return tolerate404(
    apiJson<BgpInfo>(
      "GET",
      `/api/background_process/${encodeId(id)}`,
      undefined,
      opts,
    ),
  );
}

/** ``GET /api/background_process/{id}/logs`` — tail-bounded captured
 *  output (≤200 KiB) or ``null`` (404). */
export async function fetchBgpLogs(
  id: string,
  opts?: ApiRequestOptions,
): Promise<BgpLogs | null> {
  return tolerate404(
    apiJson<BgpLogs>(
      "GET",
      `/api/background_process/${encodeId(id)}/logs`,
      undefined,
      opts,
    ),
  );
}

/** ``POST /api/background_process/{id}/stop`` — request graceful stop,
 *  returns the post-transition ``Info`` or ``null`` (404). The manager
 *  also publishes a ``background_process.updated`` event so subscribed
 *  cards refresh without polling. */
export async function stopBgp(
  id: string,
  opts?: ApiRequestOptions,
): Promise<BgpInfo | null> {
  return tolerate404(
    apiJson<BgpInfo>(
      "POST",
      `/api/background_process/${encodeId(id)}/stop`,
      undefined,
      opts,
    ),
  );
}

/** ``POST /api/background_process/{id}/restart`` — stop + respawn with the
 *  same spawn spec (the id is reused). */
export async function restartBgp(
  id: string,
  opts?: ApiRequestOptions,
): Promise<BgpInfo | null> {
  return tolerate404(
    apiJson<BgpInfo>(
      "POST",
      `/api/background_process/${encodeId(id)}/restart`,
      undefined,
      opts,
    ),
  );
}
