"""Filesystem helpers for the ``app_pack/`` directory layout.

Direct port of the legacy
``features/model-builder/scripts/qai_pack_export.py`` helpers:

* ``_link_or_copy`` — best-effort symlink + copy fallback (Windows
  non-admin / FAT32 hosts can't ``os.symlink``);
* ``_clean_for_re_export`` — incremental cleanup that keeps the heavy
  ``examples/`` / ``provenance/`` / ``weights/`` / ``assets/`` trees
  across re-exports;
* ``sha256_file`` — streaming SHA-256 over a context binary;
* ``find_context_binary`` — locate ``<model>_<label>.bin`` (label
  form) or ``<model>_<plan>.bin`` (plan form) under ``output/`` with
  case-insensitive fallback;
* ``collect_example_images`` — first ``MAX_EXAMPLES`` images under
  ``output/`` (sorted by name).
"""

from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path

from qai.model_builder.domain import Precision
from qai.model_builder.domain.value_objects import MIN_CONTEXT_BIN_SIZE

__all__ = [
    "MAX_EXAMPLES",
    "IMAGE_EXTENSIONS",
    "STALE_TOP_FILES",
    "PACK_KEEP_DIRS",
    "sha256_file",
    "link_or_copy",
    "clean_for_re_export",
    "find_context_binary",
    "collect_example_images",
]


MAX_EXAMPLES = 3
"""Number of example outputs copied into ``examples/`` per Pack."""

IMAGE_EXTENSIONS: tuple[str, ...] = (
    ".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".webp",
)

STALE_TOP_FILES: tuple[str, ...] = (
    "manifest.json",
    "runner.py",
    "requirements.txt",
    "_candidate.json",
    ".imported_at",
)
"""Top-level files always regenerated by re-export."""

PACK_KEEP_DIRS: tuple[str, ...] = (
    "examples", "provenance", "weights", "assets",
)


def sha256_file(path: Path) -> str:
    """Stream-hash ``path`` and return its hex digest."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def link_or_copy(src: Path, dst: Path) -> None:
    """Best-effort symlink ``src`` → ``dst``, falling back to copy.

    Used to materialise per-variant context binaries inside
    ``app_pack/weights/`` without duplicating the multi-hundred-MB
    files when the host platform supports symlinks.

    Failure modes (``OSError`` / ``NotImplementedError``) are
    swallowed in favour of ``shutil.copy2`` — Windows non-admin and
    FAT32 hosts cannot ``os.symlink`` and we'd rather burn the disk
    than refuse to build the Pack.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        try:
            dst.unlink()
        except OSError:
            pass
    try:
        os.symlink(src, dst)
        return
    except (OSError, NotImplementedError):
        shutil.copy2(src, dst)


def clean_for_re_export(
    pack_dir: Path,
    *,
    keep: tuple[str, ...] = PACK_KEEP_DIRS,
) -> None:
    """Incremental cleanup of an existing ``app_pack/`` directory.

    Removes the always-regenerated top-level files (manifest /
    runner / requirements / _candidate / .imported_at) plus any
    ``__pycache__`` left behind by a previous compile-check, but
    preserves the subdirectories listed in ``keep`` so re-export
    does not have to re-collect example outputs, provenance reports,
    or the per-variant weight files.

    Files outside ``keep`` at the top level that are NOT in
    :data:`STALE_TOP_FILES` are left alone — caller owns them.
    """
    if not pack_dir.is_dir():
        return
    for name in STALE_TOP_FILES:
        f = pack_dir / name
        if f.is_file():
            try:
                f.unlink()
            except OSError:
                pass
    pyc = pack_dir / "__pycache__"
    if pyc.is_dir():
        shutil.rmtree(pyc, ignore_errors=True)
    # ``keep`` is consulted by callers that want to know what to
    # preserve; the function itself only removes what's listed above.
    _ = keep


def find_context_binary(
    output_dir: Path,
    *,
    model_name: str,
    precision: Precision,
) -> Path | None:
    """Locate the context binary under ``output_dir``.

    Real Model Builder pipelines write filenames using BOTH:

    * label form ``<model>_<label>.bin`` — e.g. ``inception_v3_int8.bin``;
    * plan form  ``<model>_<plan>.bin``  — e.g. ``inception_v3_w8a8.bin``.

    We probe both (label first, plan second) with case-insensitive
    fallback. Returns the path when the file exists and meets
    :data:`qai.model_builder.domain.value_objects.MIN_CONTEXT_BIN_SIZE`,
    else ``None``.
    """
    label = precision.label
    plan = precision.plan_key

    candidate_names: list[str] = []
    seen: set[str] = set()
    for suffix in (label, plan):
        bin_name = f"{model_name}_{suffix}.bin"
        if bin_name.lower() in seen:
            continue
        seen.add(bin_name.lower())
        candidate_names.append(bin_name)

    bin_path: Path | None = None
    for bin_name in candidate_names:
        cand = output_dir / bin_name
        if cand.is_file():
            bin_path = cand
            break
        # Case-insensitive fallback inside output_dir.
        if output_dir.is_dir():
            for f in output_dir.iterdir():
                if f.name.lower() == bin_name.lower() and f.is_file():
                    bin_path = f
                    break
            if bin_path is not None:
                break

    if bin_path is None:
        return None

    try:
        size = bin_path.stat().st_size
    except OSError:
        return None
    if size < MIN_CONTEXT_BIN_SIZE:
        return None
    return bin_path


def collect_example_images(output_dir: Path) -> list[Path]:
    """Up to :data:`MAX_EXAMPLES` example images sorted by name.

    Mirrors the legacy ``collect_example_images`` exactly: ``.png`` /
    ``.jpg`` / ``.jpeg`` / ``.bmp`` / ``.tiff`` / ``.webp``.
    """
    if not output_dir.is_dir():
        return []
    images: list[Path] = []
    for f in sorted(output_dir.iterdir()):
        if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS:
            images.append(f)
        if len(images) >= MAX_EXAMPLES:
            break
    return images
